config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :session, controllers: {sessions: 'users/sessions'}
  resources :games, except: :show do
    resources :game_rules, except: :show
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_rules

  accepts_nested_attributes_for :game_rules

  validates :name, presence: true
end

app/models/game_rule.rb
class GameRule < ActiveRecord::Base
  belongs_to :game

  validates :game, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  helper_method :breadcrumbs_for

  def breadcrumbs_for(action)
    []
  end
end

app/controllers/game_rules_controller.rb
class GameRulesController < GamesController
  before_action :set_game

  def index
    @game_rules = @game.game_rules.to_a
  end

  def new
    @game_rule = @game.game_rules.build
    render :form
  end

  def create
    @game_rule = @game.game_rules.create(game_rule_params)

    if @game_rule.valid?
      redirect_to action: :edit, id: @game_rule.id
    else
      render :form
    end
  end

  def edit
    @game_rule = @game.game_rules.find(params[:id])
    render :form
  end

  def update
    @game_rule = @game.game_rules.find(params[:id])

    if @game_rule.valid?
      redirect_to action: :edit, id: @game_rule.id
    else
      render :form
    end
  end

  def destroy
    @game.game_rules.find(params[:id]).destroy!
    redirect_to action: :index
  end

  protected

  def breadcrumbs_for(action)
    super('edit') + case action
                    when 'index'
                      [['Rules', game_game_rules_path(params[:game_id])]]
                    when 'new'
                      [
                        ['Rules', game_game_rules_path(params[:game_id])],
                        ['New', new_game_game_rule_path(params[:game_id])]
                      ]
                    when 'edit'
                      [
                        ['Rules', game_game_rules_path(params[:game_id])],
                        [params[:id], edit_game_game_rule_path(params[:game_id], params[:id])]
                      ]
                    end
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def game_rule_params
    params.require(:game_rule).permit(:description)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
    render :form
  end

  def create
    @game = Game.create(game_params)

    if @game.valid?
      redirect_to action: :edit, id: @game.id
    else
      render :form
    end
  end

  def edit
    @game = Game.find(params[:id])
    render :form
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to action: :edit, id: @game.id
    else
      render :form
    end
  end

  def destroy
    Game.find(params[:id]).destroy!
    redirect_to action: :index
  end

  protected

  def breadcrumbs_for(action)
    super('edit') + case action
                    when 'index'
                      [['Games', games_path]]
                    when 'new'
                      [['Games', games_path], ['New', new_game_path]]
                    when 'edit'
                      id = params[:game_id] || params[:id]
                      [['Games', games_path], [id, edit_game_path(id)]]
                    end
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout false
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game_rules/form.html.haml
= render 'shared/errors', model: @game_rule
%h2
  Rule of
  = link_to @game.name, edit_game_path(@game)
= form_for [@game, @game_rule] do |f|
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/game_rules/index.html.haml
%h2
  Rules of
  = link_to @game.name, edit_game_path(@game)
.form-group
  = link_to 'New rule', new_game_game_rule_path, class: 'btn btn-block btn-primary'
- if @game.game_rules.any?
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th
          ID
        %th
          Description
        %th
          Created at
        %th
          Updated at
        %th
        %th
    %tbody
      - @game.game_rules.each do |game_rule|
        %tr
          %td
            = game_rule.id
          %td
            = game_rule.description
          %td
            = game_rule.created_at
          %td
            = game_rule.updated_at
          %th
            = link_to 'Edit', edit_game_game_rule_path(@game, game_rule), class: 'btn btn-block btn-success'
          %th
            = button_to 'Destroy', game_game_rule_path(@game, game_rule), class: 'btn btn-block btn-danger', method: :delete

app/views/games/form.html.haml
= render 'shared/errors', model: @game
%h2
  Game
= form_for @game do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-primary'
- if @game.persisted?
  = link_to 'Rules', game_game_rules_path(@game)

app/views/games/index.html.haml
%h2
  Games
.form-group
  = link_to 'New game', new_game_path, class: 'btn btn-block btn-primary'
- if @games.any?
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th
          ID
        %th
          Name
        %th
          Created at
        %th
          Updated at
        %th
        %th
    %tbody
      - @games.each do |game|
        %tr
          %td
            = game.id
          %td
            = game.name
          %td
            = game.created_at
          %td
            = game.updated_at
          %th
            = link_to 'Edit', edit_game_path(game), class: 'btn btn-block btn-success'
          %th
            = button_to 'Destroy', game_path(game), class: 'btn btn-block btn-danger', method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title PvpcAdmin
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .col-lg-10.col-lg-offset-1
      %nav.navbar.navbar-default
        .container-fluid
          %ul.nav.navbar-nav.navbar-left
            %li
              = link_to 'Games', games_path
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Sign out', destroy_user_session_path, method: :delete
      %ol.breadcrumb
        - breadcrumbs_for(action_name).each do |label, path|
          %li
            = link_to label, path
      = yield

app/views/shared/_errors.html.haml
- if model.errors.any?
  .form-group.text-danger
    %ul
      - model.errors.full_messages.each do |message|
        %li
          %strong
            = message